// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxiaxpgyqpmnkmebvvap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54aWF4cGd5cXBtbmttZWJ2dmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODA2NzMsImV4cCI6MjA2MDA1NjY3M30.3QagXyWbGHR4GmTZFW9M6_7m1kR-0ZfP52V7wLCqrbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});